import AuthContext from "@/providers/Auth/Auth";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContext>{children}</AuthContext>
        <Toaster />

        <script src="https://unpkg.com/react@16.3.1/umd/react.development.js"></script>
        <script src="https://unpkg.com/react-beautiful-dnd@x.x.x/dist/react-beautiful-dnd.js"></script>
        <script src="https://unpkg.com/react-dom@16.3.1/umd/react-dom.development.js"></script>
      </body>
    </html>
  );
}
